version: '3'
services:
  app:
    image: app
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/myapp
      - ./logs/php/:/var/log/
    working_dir: "/myapp"
  php:
    depends_on:
      - app
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/myapp
    working_dir: "/myapp"
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/myapp
      - ./logs/nginx/:/var/log/nginx
    working_dir: "/myapp"
    links:
      - phpmyadmin:phpmyadmin
  mysql:
    build:
      context: ./
      dockerfile: docker/mysql/Dockerfile
    ports:
      - 3306:3306
    env_file:
      - docker/mysql/mysql.env
    volumes:
      - db-data:/var/lib/mysql
      - ./logs/mysql/:/var/log/mysql
  composer:
    depends_on:
      - app
    build:
      context: ./
      dockerfile: docker/composer/Dockerfile
    volumes:
      - ./:/myapp
    working_dir: "/myapp"
  phpmyadmin:
    build:
      context: ./
      dockerfile: docker/phpmyadmin/Dockerfile
    env_file:
      - docker/phpmyadmin/phpmyadmin.env
volumes:
  db-data:
